name: Update Codespaces

on:
  push:
    branches:
      - main  

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Trigger Codespace Rebuild
        run: |
          echo "Rebuilding all Codespaces..."
          gh codespace rebuild --all
